Repository pyTooling/Actions, pull requests merged in 2021-12, with the labels that each got.

#10 add Action 'releaser'
  .github/workflows/TestReleaser.yml
  releaser/Dockerfile
  releaser/README.md
  releaser/action.yml
  releaser/composite/action.yml
  releaser/pyproject.toml
  releaser/releaser.py
Labels: enhancement

#13 Add a job template to publish unit test results
  .github/workflows/PublishTestResults.yml
  ExamplePipeline.yml
  README.md
Labels: enhancement

#11 Add licenses
  .github/workflows/ArtifactCleanUp.yml
  .github/workflows/BuildTheDocs.yml
  .github/workflows/CoverageCollection.yml
  .github/workflows/Package.yml
  .github/workflows/Parameters.yml
  .github/workflows/PublishOnPyPI.yml
  .github/workflows/PublishTestResults.yml
  .github/workflows/PublishToGitHubPages.yml
  .github/workflows/Release.yml
  .github/workflows/StaticTypeCheck.yml
  .github/workflows/TestReleaser.yml
  .github/workflows/UnitTesting.yml
  .github/workflows/VerifyDocs.yml
  ExamplePipeline.yml
  LICENSE.md
  README.md
  doc/Doc-License.rst
  releaser/action.yml
  releaser/composite/action.yml
  releaser/releaser.py
  with-post-step/action.yml
  with-post-step/main.js
Labels: documentation, enhancement

#21 Package: support either 'build' or 'setuptools'
  .github/workflows/Package.yml
Labels: enhancement

#25 v0.2.2
  .github/workflows/TestReleaser.yml
  releaser/Dockerfile
  releaser/README.md
  releaser/action.yml
  releaser/releaser.py
Labels: Enhancement, CI: GitHub Actions, Releaser

#28 v0.2.3
  releaser/composite/action.yml
Labels: Releaser, Release

#29 Pytest using pyproject.toml.
  .github/workflows/CoverageCollection.yml
  .github/workflows/UnitTesting.yml
  README.md
Labels: Enhancement, Pipeline
